# NOTE: arm images haven't been tested
services:
  speaches-cuda:
    image: fedirz/speaches:cuda
    build:
      dockerfile: Dockerfile.cuda
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
      tags:
        - fedirz/speaches:cuda
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
  speaches-cpu:
    image: fedirz/speaches:cpu
    build:
      dockerfile: Dockerfile.cpu
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
      tags:
        - fedirz/speaches:cpu
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
    ports:
      - 8000:8000
