[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
faster-whisper = "^1.0.2"
pydantic = "^2.7.1"
fastapi = "^0.111.0"
uvicorn = "^0.29.0"
python-multipart = "^0.0.9"
soundfile = "^0.12.1"
pydantic-settings = "^2.2.1"
websockets = "^12.0"
numpy = "^1.26.4"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
pytest-asyncio = "^0.23.6"
httpx = "^0.27.0"
httpx-ws = "^0.6.0"
pytest-xdist = "^3.6.1"



[tool.poetry.group.client.dependencies]
httpx = "^0.27.0"
httpx-ws = "^0.6.0"

[tool.ruff]
target-version = "py311"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
